// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:studio_packet/aidata/data/model/chat/folder.dart';
import 'package:studio_packet/aidata/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChatConfigAdapter());
    registerAdapter(ChatContentAdapter());
    registerAdapter(ChatContentTypeAdapter());
    registerAdapter(ChatFolderAdapter());
    registerAdapter(ChatFolderAdapter());
    registerAdapter(ChatHistoryAdapter());
    registerAdapter(ChatHistoryItemAdapter());
    registerAdapter(ChatRoleAdapter());
    registerAdapter(ChatSettingsAdapter());
    registerAdapter(ChatTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ChatConfigAdapter());
    registerAdapter(ChatContentAdapter());
    registerAdapter(ChatContentTypeAdapter());
    registerAdapter(ChatFolderAdapter());
    registerAdapter(ChatFolderAdapter());
    registerAdapter(ChatHistoryAdapter());
    registerAdapter(ChatHistoryItemAdapter());
    registerAdapter(ChatRoleAdapter());
    registerAdapter(ChatSettingsAdapter());
    registerAdapter(ChatTypeAdapter());
  }
}
